Created a function "validateUserCredentials()" to validate the user credentials during config set, check-node, prep-node execution.
platform9/pf9ctl pull request #104
Opened 2021-03-01 13:34 UTC by AnirudhPokala

<img width="572" alt="Screenshot 2021-03-01 at 6 58 58 PM" src="https://user-images.githubusercontent.com/77390180/109503786-b5f56580-7ac0-11eb-8787-f35a958041ae.png">
<img width="572" alt="Screenshot 2021-03-01 at 6 58 17 PM" src="https://user-images.githubusercontent.com/77390180/109503789-b7269280-7ac0-11eb-886a-26f58a7e2539.png">

2021-03-01 13:43 UTC, nikhilbandi commented on cmd/checkNode.go
> +		zap.S().Fatalf("Invalid Credentials (Username/Password/Service), run 'pf9ctl config set' !!")
Better error message is: "Invalid credentials (Username/ Password/ Account), run 'pf9ctl config set' with correct credentials. "

2021-03-01 13:45 UTC, AnirudhPokala commented on cmd/checkNode.go
> +		zap.S().Fatalf("Invalid Credentials (Username/Password/Service), run 'pf9ctl config set' !!")
Done Nikhil edited the error message.

2021-03-01 13:46 UTC, anupbarve commented on cmd/checkNode.go
> +	c = validateUserCredentials(ctx)
I don't like the idea of a validation function returning a client and operation flow using it. It is non-intuitive. We should pass the client to the `validateUserCredentials`.

2021-03-01 13:50 UTC, AnirudhPokala commented on cmd/checkNode.go
> +	c = validateUserCredentials(ctx)
Ok anup will create a seperate function to create the client and will pass it to validateUserCredentials. Is it ok?

2021-03-02 07:40 UTC, anupbarve requested changes

2021-03-02 07:40 UTC, anupbarve commented on cmd/checkNode.go
> +}
We should move this to config.go

2021-03-02 07:40 UTC, anupbarve commented on cmd/checkNode.go
> +}
This should not be a different function at all. We should simply unfold it and call it in respective cmd/<command.go> files.

2021-03-02 09:18 UTC, AnirudhPokala commented on cmd/checkNode.go
> +}
sure anup done.

2021-03-02 09:18 UTC, AnirudhPokala commented on cmd/checkNode.go
> +}
ok anup done once review it.

2021-03-02 10:07 UTC, anupbarve approved these changes
Please take help from @devidask27 to run TC build and post the TC link here.

2021-03-02 10:11 UTC, sahil-lakhwani commented on cmd/config.go
> +func validateUserCredentials(pmk.Config, pmk.Client) {
I think this function should return error instead of failing in a fatal way.

2021-03-02 10:27 UTC, AnirudhPokala commented on cmd/config.go
> +func validateUserCredentials(pmk.Config, pmk.Client) {
Ya we can do that, but then we are adding same error message line thirce in config.go, checkNode.go, prepNode.go. So added that error validation in function itself.

2021-03-02 10:34 UTC, AnirudhPokala commented
> Please take help from @devidask27 to run TC build and post the TC link here.

Ya Anup its working fine. 

http://teamcity.platform9.horse:8111/buildConfiguration/Pf9project_Platform9Components_Pf9ctl/1452392

2021-03-02 10:37 UTC, sahil-lakhwani commented on cmd/config.go
> +func validateUserCredentials(pmk.Config, pmk.Client) {
I think that should be fine. This function can return an error message, which the callers can use however they want

2021-03-02 10:53 UTC, AnirudhPokala commented on cmd/config.go
> +func validateUserCredentials(pmk.Config, pmk.Client) {
Ya Sahil modified it, once review it.

2021-03-02 11:26 UTC, sahil-lakhwani approved these changes

2021-03-02 11:28 UTC, merged