injected segment key
platform9/pf9ctl pull request #144
Opened 2021-04-22 09:52 UTC by AnirudhPokala

Segment key injected

2021-04-23 06:17 UTC, nikhilbandi requested changes
Please handle the Else case as suggested by Anup.

2021-04-26 10:25 UTC, ParagDoke reviewed
Must squash commits before merging. Currently there are 11 of them.

2021-04-26 10:25 UTC, ParagDoke commented on pkg/pmk/segment.go
> +//var SegmentWriteKey = os.Getenv("SEGMENT_KEY_PRD_PMKFT")
Please drop the comment.

2021-04-26 10:25 UTC, ParagDoke commented on pkg/pmk/segment.go
> +	// Local Case.
Comment should read "Local build case" to unambiguously capture if the build is local or run is local.

2021-04-26 10:27 UTC, AnirudhPokala commented on pkg/pmk/segment.go
> +//var SegmentWriteKey = os.Getenv("SEGMENT_KEY_PRD_PMKFT")
Sure dropped off.

2021-04-26 10:27 UTC, AnirudhPokala commented on pkg/pmk/segment.go
> +	// Local Case.
Sure will modify.

2021-04-26 10:34 UTC, anupbarve approved these changes

2021-04-26 11:11 UTC, devidask27 approved these changes

2021-04-26 11:17 UTC, nikhilbandi approved these changes
Looks good.

2021-04-26 11:19 UTC, merged