Added supportBundle test file
platform9/pf9ctl pull request #151
Opened 2021-05-07 09:22 UTC by ShaunakJoshi1407

>Added unit test cases for supportBundle
>Modified the S3Upload and the RemoveBundle functions in supportBundle.go for ease in testing.
>Added additional comments in supportBundle.go

2021-05-13 04:44 UTC, devidask27 commented on pkg/supportBundle/supportBundle.go
> +	//var exec cmdexec.Executor
Remove this

2021-05-13 05:01 UTC, AnirudhPokala commented on pkg/supportBundle/supportBundle.go
> +		zap.S().Debug("Error removing generated bundle from local machine", errremove)
We will even remove generated bundle in remote case also right?

2021-05-13 05:06 UTC, devidask27 commented on pkg/supportBundle/supportBundle.go
> +func GenSupportBundle(exec cmdexec.Executor, timestamp time.Time) (string, error) {
This function executes multiple commands. and we are only testing it for nil error. i think we should add failure cases as well.

2021-05-13 05:33 UTC, ShaunakJoshi1407 commented on pkg/supportBundle/supportBundle.go
> +	//var exec cmdexec.Executor
Ok will do

2021-05-13 05:49 UTC, ShaunakJoshi1407 commented on pkg/supportBundle/supportBundle.go
> +		zap.S().Debug("Error removing generated bundle from local machine", errremove)
Yes it will get removed even in the remote case

2021-05-13 05:50 UTC, ShaunakJoshi1407 commented on pkg/supportBundle/supportBundle.go
> +		zap.S().Debug("Error removing generated bundle from local machine", errremove)
I will change this particular message

2021-05-17 05:17 UTC, anupbarve requested changes

2021-05-17 05:17 UTC, anupbarve commented on cmd/supportBundle_test.go
> +			assert.Equal(t, tc.want.err, err1)
Could you reuse this implementation instead? https://github.com/platform9/pf9ctl/blob/master/pkg/test_utils/test_utils.go#L12
This will keep things uniform all across the code.

Please change this all across the testing code.

2021-05-17 06:19 UTC, ShaunakJoshi1407 commented on cmd/supportBundle_test.go
> +			assert.Equal(t, tc.want.err, err1)
Sure will make the changes

2021-05-17 09:43 UTC, anupbarve approved these changes

2021-05-17 09:47 UTC, merged