Private/devidask/attach node
platform9/pf9ctl pull request #152
Opened 2021-05-12 11:39 UTC by devidask27

added attach-node command

2021-05-17 07:36 UTC, anupbarve requested changes
First pass.
Added some comments that need to be addressed.

2021-05-17 07:36 UTC, anupbarve commented on cmd/attachNode.go
> +	Long:  "attaches node to kubernetes cluster",
Need to add more information here.
Example: 
- About considerations around combinations of -m and -w working together

2021-05-17 07:36 UTC, anupbarve commented on cmd/attachNode.go
> +			return errors.New("only one argument is required")
Refine this to :
"Only cluster name is accepted as a parameter"

2021-05-17 07:36 UTC, anupbarve commented on cmd/attachNode.go
> +			return errors.New("cluster name is required")
Refine this to:
"Cluster name is required for attach-node"

2021-05-17 07:36 UTC, anupbarve commented on cmd/attachNode.go
> +			zap.S().Infof("Unable to find host with IP %v please try again or run prep-node first", ip)
Need to return from here with an error ?

2021-05-17 07:36 UTC, anupbarve commented on cmd/attachNode.go
> +	return status
What happens when this curl command fails ?
Need to check the status and handle error accordingly.

2021-05-17 07:36 UTC, anupbarve commented on pkg/pmk/cluster.go
> +		keystoneAuth.ProjectID, keystoneAuth.Token, nodeIDs, "workeer")
typo : workeer ?

2021-05-17 09:54 UTC, devidask27 commented on cmd/attachNode.go
> +	Long:  "attaches node to kubernetes cluster",
Done

2021-05-17 09:54 UTC, devidask27 commented on cmd/attachNode.go
> +			return errors.New("only one argument is required")
Added

2021-05-17 09:54 UTC, devidask27 commented on cmd/attachNode.go
> +			return errors.New("cluster name is required")
Added

2021-05-17 09:54 UTC, devidask27 commented on cmd/attachNode.go
> +			zap.S().Infof("Unable to find host with IP %v please try again or run prep-node first", ip)
Done

2021-05-17 09:55 UTC, devidask27 commented on cmd/attachNode.go
> +	return status
Added error case

2021-05-17 09:55 UTC, devidask27 commented on pkg/pmk/cluster.go
> +		keystoneAuth.ProjectID, keystoneAuth.Token, nodeIDs, "workeer")
Fixed

2021-05-17 11:47 UTC, anupbarve requested changes
One thing that is missing in this implementation is that segment events are not added for both success or failure case.
Need to add it.

2021-05-18 08:25 UTC, anupbarve reviewed
Some minor comments. Else, looks good to me.
Please go ahead and add tests since the core logic is now reviewed.

2021-05-18 08:25 UTC, anupbarve commented on cmd/attachNode.go
> +				zap.S().Info("Worker node(s) attached to cluster")
Can you please add hostid to this log message ?

2021-05-18 08:25 UTC, anupbarve commented on cmd/attachNode.go
> +				zap.S().Info("Master node(s) attached to cluster")
Can you please add hostid to this log message ?

2021-05-18 08:25 UTC, anupbarve commented on cmd/attachNode.go
> +	status = strings.TrimSpace(strings.Trim(status, "\n\""))
Log status here.

2021-05-26 05:24 UTC, anupbarve approved these changes
Please update README.md before checkin.

2021-05-27 03:11 UTC, merged