Updated README.md
platform9/pf9ctl pull request #154
Opened 2021-05-18 08:25 UTC by ShaunakJoshi1407

-Added requirements of pf9ctl.
-Added usage along with description of the commands in use.
-Explained each command with a sample code snippet.

2021-05-19 09:29 UTC, anupbarve requested changes

2021-05-19 09:29 UTC, anupbarve commented on README.md
> +  This command will perform the prerequisite check before a node can be added to the cluster. It checks for the following:
s/check/checks
Could we add which checks are mandatory and which ones are optional ?

2021-05-19 09:29 UTC, anupbarve commented on README.md
> + This command prepares a node to be ready to be added to a cluster. It installs all the required pre-requisites on the nodes and installs the Platform9 host agent and other required software on the n
Replace above text with:

This command onboards a node. It installs platform9 packages on the host. After completion of this command, the node is available to be managed on the Platform9 control plane.

2021-05-19 10:00 UTC, ShaunakJoshi1407 commented on README.md
> +  This command will perform the prerequisite check before a node can be added to the cluster. It checks for the following:
Ok will add that

2021-05-19 10:02 UTC, ShaunakJoshi1407 commented on README.md
> + This command prepares a node to be ready to be added to a cluster. It installs all the required pre-requisites on the nodes and installs the Platform9 host agent and other required software on the n
Ok will replace this text

2021-05-20 08:27 UTC, anupbarve approved these changes

2021-05-20 08:33 UTC, merged