Moved swap off to check-node
platform9/pf9ctl pull request #155
Opened 2021-05-18 13:19 UTC by devidask27

Moved swap off functionality from prep-node to check-node

./pf9ctl prep-node -i 172.20.7.2 -u ubuntu -s /home/ubuntu/.ssh/mykey
✓ Loaded Config Successfully
✓ Removal of existing CLI
✓ Existing Platform9 Packages Check
✓ Required OS Packages Check
✓ SudoCheck
✓ CPUCheck
✓ DiskCheck
✓ MemoryCheck
✓ PortCheck
✓ Existing Kubernetes Cluster Check
✓ Disabling swap and removing swap in fstab

✓ Completed Pre-Requisite Checks successfully

------------------------------------------------------------
./pf9ctl prep-node -i 172.20.7.109 -u ubuntu -s /home/ubuntu/.ssh/mykey --disableSwapOff
✓ Loaded Config Successfully
✓ Removal of existing CLI
x Existing Platform9 Packages Check - Platform9 packages already exist. These must be uninstalled.
✓ Required OS Packages Check
✓ SudoCheck
✓ CPUCheck
✓ DiskCheck
✓ MemoryCheck
x PortCheck - Following port(s) should not be in use: 10250, 3306
x Existing Kubernetes Cluster Check - A Kubernetes cluster is already running on node

x Required pre-requisite check(s) failed.

2021-05-19 04:26 UTC, anupbarve requested changes

2021-05-19 04:26 UTC, anupbarve commented on pkg/pmk/checkNode.go
> +	}
Let us not convolute the logic with some checks here and some in platform module. 
It becomes very hard to maintain such code.
Could you please treat this check similar to other checks and make it a mandatory one ?

2021-05-19 05:03 UTC, anupbarve commented
Could you also test the failure case, where disable swapoff failure is manually induced and then check-node detects it.

2021-05-24 06:26 UTC, anupbarve requested changes
1.  Did you try to induce failure in swapoff disable function ?
2. Can we add as test case for this functionality in our existing test case infra ?

2021-05-24 06:26 UTC, anupbarve commented on pkg/platform/debian/debian.go
> +	if !util.SwapOffDisabled {
Can we move this check inside `disableSwap` swap function itself. 
This will make it self-sufficient.

2021-05-24 06:26 UTC, anupbarve commented on pkg/platform/debian/debian.go
> +		return false, errors.New("error occured while removing swap")
s/removing/disabling

2021-05-24 06:26 UTC, anupbarve commented on pkg/platform/centos/centos.go
> +		return false, errors.New("error occured while removing swap")
s/removing/disabling

2021-05-24 06:26 UTC, anupbarve commented on pkg/platform/centos/centos.go
> +	if !util.SwapOffDisabled {
Can we move this to disableSwap function, to make it self-sufficient?

2021-05-24 06:32 UTC, devidask27 commented on pkg/platform/debian/debian.go
> +	if !util.SwapOffDisabled {
I think we cannot move. because whether to call disableSwap or not is depends on this flag.

2021-05-24 06:33 UTC, devidask27 commented on pkg/platform/centos/centos.go
> +	if !util.SwapOffDisabled {
I think we cannot move. because whether to call disableSwap or not is depends on this flag.

2021-05-24 06:45 UTC, anupbarve commented on pkg/platform/debian/debian.go
> +	if !util.SwapOffDisabled {
I am proposing something like this:

`
disableSwap {
 if util.SwapOffDisabled
     return
logic for disableSwap
}
`

2021-05-24 07:02 UTC, devidask27 commented on pkg/platform/debian/debian.go
> +	if !util.SwapOffDisabled {
yes we can do that. 
if util.SwapOffDisabled 
return false, nill

But check node will fail because this is mandatary check

2021-05-24 08:37 UTC, anupbarve approved these changes

2021-05-24 09:11 UTC, merged