Private/devidask/dpkg lock check
platform9/pf9ctl pull request #163
Opened 2021-06-13 10:09 UTC by devidask27

- Added pre-requisite check to check if there is lock on dpkg and apt.
- Added pre-requisite check to check if system is booted with systemd(PID=1)

2021-06-21 06:01 UTC, anupbarve requested changes
Need to add tests for these checks.

2021-06-22 09:36 UTC, anupbarve commented on pkg/platform/debian/debian.go
> +}
Please remove this check from the current PR. 
We are not yet sure if it works.
Also remove the corresponding test cases. 
We will take it up as part of another PR.

2021-06-22 10:01 UTC, devidask27 commented on pkg/platform/debian/debian.go
> +}
Okay

2021-06-22 10:17 UTC, anupbarve commented on pkg/platform/centos/centos.go
> +}
Also need to remove this one

2021-06-22 10:22 UTC, devidask27 commented on pkg/platform/centos/centos.go
> +}
Done

2021-06-22 10:48 UTC, anupbarve approved these changes

2021-06-22 10:50 UTC, merged