Automation
platform9/pf9ctl pull request #220
Opened 2021-11-01 12:55 UTC by sahil-lakhwani

Thia PR is to make pf9ctl be allowed to run without any user prompt
Two major additions are:
- `--dt` flag -  Adding this flag will disable all user prompts. Any errors (missing flags, etc) are reported immediately and the cLI exits with non 0 code
 - `--mfa` - This is for commands like check-node & prep-node to allow users to push current MFA token

2021-11-02 06:35 UTC, nikhilbandi commented on cmd/config.go
> +const MaxLoopNoConfig = 3
Can this be put in constants file?

2021-11-02 06:40 UTC, nikhilbandi commented on cmd/config.go
> +	configCmdSet.Flags().StringVarP(&cfg.Fqdn, "account_url", "u", "", "sets account_url")
Can't we have a common init() function somewhere instead of repeating this chunk of code in every file?

2021-11-02 07:15 UTC, nikhilbandi commented on cmd/root.go
> +	rootCmd.PersistentFlags().BoolVar(&detach, "dt", false, "disable all user prompts")
Is "dt" a commonly used abbreviation? Can we think of something more intuitive?

2021-11-02 07:23 UTC, nikhilbandi commented on pkg/config/config.go
> +	if loc == "amazon.json" {
Shouldn't the json filenames be part of the constants file?

2021-11-02 07:46 UTC, nikhilbandi commented on pkg/pmk/node.go
> +// func FetchRegionFQDN(ctx config.Config, auth keystone.KeystoneAuth) (string, error) {
This can be removed instead of just being commented.

2021-11-10 11:09 UTC, sahil-lakhwani commented on cmd/config.go
> +const MaxLoopNoConfig = 3
This wasn't needed. Thanks for pointing.

2021-11-10 11:09 UTC, sahil-lakhwani commented on cmd/config.go
> +	configCmdSet.Flags().StringVarP(&cfg.Fqdn, "account_url", "u", "", "sets account_url")
I think it is better this way so that flags for respective commands remain local

2021-11-10 11:12 UTC, sahil-lakhwani commented on pkg/config/config.go
> +	if loc == "amazon.json" {
This is something from existing code. We can remove this in a separate PR
I'm thinking to do this in a better way so - these file names are just dummy, no file with such names is even created

2021-11-10 11:12 UTC, sahil-lakhwani commented on pkg/pmk/node.go
> +// func FetchRegionFQDN(ctx config.Config, auth keystone.KeystoneAuth) (string, error) {
removed this and some more unused code, thanks for noticing+

2021-11-11 06:19 UTC, anupbarve requested changes

2021-11-11 06:19 UTC, anupbarve commented on cmd/attachNode.go
> +	}
Can't this decision be made inside config module by passing detachedMode flag to a generic function ?
This will reduce the load on all the callers (existing and future ones) to invoke the same conditional logic.

2021-11-11 06:19 UTC, anupbarve commented on cmd/checkNode.go
> +			zap.S().Fatal(err.Error())
Need to add the context of this fatal failure as a message.
Something like "Failed to check sudo password"

2021-11-11 06:19 UTC, anupbarve commented on cmd/cloudProviders.go
> +		err = config.LoadConfigInteractive("google.json", cfg, objects.NodeConfig{})
Seems like the only difference in all the `*ProviderRun` functions is the json file. 
Could we factor out all the common code in those functions ?

2021-11-11 06:19 UTC, anupbarve commented on cmd/prepNode_test.go
> -}
Why deleted ? How can we replace this test if not valid anymore?

2021-11-11 08:16 UTC, sahil-lakhwani commented on pkg/objects/objects.go
> +package objects
Putting those structs in `config` package causes a import cycle.

2021-11-11 08:22 UTC, sahil-lakhwani commented on cmd/attachNode.go
> +	}
I think that is intentional to allow callers to do things before and after loading config
For example,
https://github.com/platform9/pf9ctl/blob/76a4d881f0454bd0dd256479d94ab85fd383e9df/cmd/cloudProviders.go#L77-L83

2021-11-11 08:26 UTC, sahil-lakhwani commented on cmd/cloudProviders.go
> +		err = config.LoadConfigInteractive("google.json", cfg, objects.NodeConfig{})
Yes we can.  A lot of that is existing code. As mentioned above in a reply to Nikhil, I would like to take it in a different PR

2021-11-11 08:27 UTC, sahil-lakhwani commented on cmd/prepNode_test.go
> -}
The functioned being tested has been moved. I'll add a test case for there.

2021-11-11 08:27 UTC, sahil-lakhwani commented on pkg/keystone/keystone.go
> +func FetchRegionFQDN(fqdn string, region string, auth KeystoneAuth) (string, error) {
Okay,I'll update this

2021-11-11 10:01 UTC, sahil-lakhwani commented on cmd/checkNode.go
> +			zap.S().Fatal(err.Error())
Added this

2021-11-15 04:47 UTC, anupbarve approved these changes
lgtm.
This is a relatively large change. Could you please document all the testing done in the PR description ?

2021-11-15 10:22 UTC, merged