Private/devidas/attach node spinner
platform9/pf9ctl pull request #266
Opened 2022-01-20 11:32 UTC by devidask27

2022-01-20 12:37 UTC, nikhilbandi commented on cmd/attachNode.go
>  			}
Shouldn't we have else condition where we print console message and log saying "no worker node available to attach to the cluster"?

2022-01-20 12:38 UTC, nikhilbandi commented on cmd/attachNode.go
>  			}
Same as above, just for Master nodes. Shouldn't the relevant message be printed in the else condition?

2022-01-20 12:40 UTC, nikhilbandi commented on cmd/attachNode.go
> +
Add comment "//Check if the node being attached is already attached to any cluster."

2022-01-20 12:41 UTC, nikhilbandi requested changes
Please take a look at the comments mentioned.

2022-01-20 12:56 UTC, devidask27 commented on cmd/attachNode.go
>  			}
No Nikhil, we are first printing if it is attached to any cluster or not. So there is no node means that are already connected.

2022-01-20 13:42 UTC, devidask27 commented on cmd/attachNode.go
>  			}
Done

2022-01-20 13:42 UTC, devidask27 commented on cmd/attachNode.go
>  			}
Done

2022-01-20 13:45 UTC, devidask27 commented on cmd/attachNode.go
> +
Done

2022-01-21 07:28 UTC, nikhilbandi approved these changes
Approving.

2022-01-21 08:53 UTC, merged