add option to attach node using cluster uuid
platform9/pf9ctl pull request #275
Opened 2022-02-03 08:08 UTC by OmkarDeshpande7

- Added option to attach a node to a cluster using cluster uuid
- The new "uuid" flag is optional 
- Even if we specify the "uuid" flag, we would have to put some dummy cluster name
- This is to ensure that the modifications would not introduce any breaking changes (in case some automation is already done somewhere using pf9ctl)

2022-02-03 16:07 UTC, erwinvaneyk commented on pkg/qbert/qbert.go
> +		return false, "", fmt.Errorf("Couldn't query the qbert Endpoint: %d", resp.StatusCode)
* Errors should not be capitalized
* Avoid colloquialisms
```suggestion
		return false, "", fmt.Errorf("could not query the qbert Endpoint: %d", resp.StatusCode)
```
(same goes for other errors)

2022-02-03 16:07 UTC, erwinvaneyk commented on cmd/attachNode.go
> +		}
I don't think a cluster can have an empty name, so this `exist` is a bit unnecessary.

2022-02-03 16:07 UTC, erwinvaneyk commented on cmd/attachNode.go
> +	attachNodeCmd.Flags().StringVarP(&clusterUuid, "uuid", "u", "", "cluster uuid")
Try to make this a full sentence 😉

2022-02-03 16:07 UTC, erwinvaneyk commented on cmd/attachNode.go
> +			// even if '-u' option is specified use some dummy cluster name
I think the flag is already set as this point, so you can use it in this check and avoid this dummy thing

2022-02-04 05:26 UTC, OmkarDeshpande7 commented on cmd/attachNode.go
> +		_, cluster_uuid, _ = c.Qbert.CheckClusterExists(clusterName, projectId, token)
Hi @erwinvaneyk, good point. But I did not want to disturb the next bit of code where the variable name is already used in that fashion.

2022-02-07 11:53 UTC, erwinvaneyk approved these changes
Looks good, but a review from @devidask27 or @nikhilbandi is needed too

2022-02-08 11:05 UTC, anupbarve requested changes
- Please add screenshots of the test cases executed manually.
- README needs to be updated, since we are changing the CLI options.
- This would also need changes to the pf9ctl external facing docs. This needs to be tracked.
cc: @devidask27 @nikhilbandi

2022-02-09 10:06 UTC, anmolsachan commented on cmd/attachNode.go
> +	attachNodeCmd.Flags().StringVarP(&clusterUuid, "uuid", "u", "", "uuid of a cluser to attach the node to")
```suggestion
	attachNodeCmd.Flags().StringVarP(&clusterUuid, "uuid", "u", "", "uuid of the cluster to attach the node to.")
```

2022-02-14 11:44 UTC, OmkarDeshpande7 commented on cmd/attachNode.go
> +	attachNodeCmd.Flags().StringVarP(&clusterUuid, "uuid", "u", "", "uuid of a cluser to attach the node to")
Done

2022-02-23 12:11 UTC, anupbarve requested changes

2022-02-23 12:11 UTC, anupbarve commented on cmd/attachNode.go
> +	attachNodeCmd.Flags().MarkHidden("uuid")
why is this hidden ?

2022-02-23 12:11 UTC, anupbarve commented on pkg/qbert/qbert.go
> +		return "", fmt.Errorf("could not query the qbert Endpoint: %d", resp.StatusCode)
nit: 
%s/Endpoint/endpoint

2022-02-23 12:33 UTC, OmkarDeshpande7 commented on pkg/qbert/qbert.go
> +		return "", fmt.Errorf("could not query the qbert Endpoint: %d", resp.StatusCode)
done

2022-02-23 13:16 UTC, OmkarDeshpande7 commented on cmd/attachNode.go
> +	attachNodeCmd.Flags().MarkHidden("uuid")
Hi @anupbarve, Thanks!
Initially, it was needed for internal usage and testing. There is no specific reason to mark this hidden. We can make the flag public, should we?

2022-02-24 05:29 UTC, anupbarve commented on cmd/attachNode.go
> +	attachNodeCmd.Flags().MarkHidden("uuid")
I would like @anmolsachan to comment on this.
IMO, I see this as a value add that can be made public.

2022-02-24 08:31 UTC, OmkarDeshpande7 commented
![Screenshot 2022-02-24 at 2 00 01 PM](https://user-images.githubusercontent.com/47773862/155487429-c5a119fe-134b-4598-b319-7fb67ea7b8d3.png)

2022-02-24 10:43 UTC, anmolsachan commented
Hey @OmkarDeshpande7, Can you please elaborate on the need for this PR? Any engineering/customer-facing requirements?

2022-02-24 12:13 UTC, OmkarDeshpande7 commented
Hi @anmolsachan,
There aren't any customer-facing requirements that I am aware of. However, previously `pf9ctl` allowed only cluster name to be supplied as a parameter to `attach-node`. Now, keeping in mind that we allow clusters with the same names to be created in qbert, this causes `pf9ctl` to attach the node to the wrong cluster if two clusters of the same name are present (OR even fail).
This issue was noticed during testing of CAPI related work (Since we are using pf9ctl based automation to onboard a node to DU). So, having UUID as a parameter would help to reduce unintentional errors.
Just highlighting again, there is no specific reason to mark this flag as hidden.

2022-02-24 18:00 UTC, anmolsachan commented
Thanks, @OmkarDeshpande7, I think that is a good enough reason. I would let @anupbarve @devidask27 provide final approval.

2022-03-15 07:45 UTC, devidask27 commented on pkg/qbert/qbert.go
> -	CheckClusterExistsWithUuid(uuid, projectID, token string) (string, error)
Why this is removed ?

2022-03-15 08:04 UTC, OmkarDeshpande7 commented on pkg/qbert/qbert.go
> -	CheckClusterExistsWithUuid(uuid, projectID, token string) (string, error)
It has been restored

2022-03-15 09:13 UTC, devidask27 commented
@OmkarDeshpande7 Also update the README.

2022-03-15 10:18 UTC, devidask27 requested changes

2022-03-15 10:18 UTC, devidask27 commented on pkg/qbert/qbert.go
> +	return fmt.Sprintf("error finding cluster with uuid %s", uuid), nil
err should not be nil in this case, return some error message.

2022-03-15 10:48 UTC, OmkarDeshpande7 commented on pkg/qbert/qbert.go
> +	return fmt.Sprintf("error finding cluster with uuid %s", uuid), nil
Done

2022-03-15 11:03 UTC, devidask27 approved these changes
LGTM

2022-03-15 11:08 UTC, OmkarDeshpande7 commented on cmd/attachNode.go
> +	if clusterUuid != "" {
Done

2022-03-16 05:57 UTC, anupbarve approved these changes
lgtm

2022-03-16 06:01 UTC, merged