Remove option of existing packages on re-run
platform9/pf9ctl pull request #276
Opened 2022-02-03 09:24 UTC by joey00072

Option to remove existing packages to commands check-node,prep-node
and bootstrap
Moved pf9ctl downloaded packages removing commands to pmk/decomissionNode
Moved func hostId,getIp to pmk/network to avoid circular import

2022-02-08 11:29 UTC, anupbarve requested changes
Please post screenshots of the testing done.
@devidask27 you should also review this change since you own the CLI code.

2022-02-08 11:29 UTC, anupbarve commented on pkg/pmk/checkNode.go
> +			fmt.Print("Decomissing Node ...\n\n")
nit:
%s/Decomissing/Decommissioning

2022-02-08 11:29 UTC, anupbarve commented on pkg/pmk/decomissionNode.go
> +}
Do you still need `RunCommandWait` in cmd/decomissionNode.go ?

2022-02-08 13:32 UTC, joey00072 commented
When irevious  installation  exists 

<img width="1440" alt="Screenshot 2022-02-08 at 6 53 52 PM" src="https://user-images.githubusercontent.com/35176826/152996706-f4fceb9e-8e3e-4611-942f-dee258a7a1f1.png">

Clean install

<img width="1440" alt="Screenshot 2022-02-08 at 6 55 40 PM" src="https://user-images.githubusercontent.com/35176826/152997113-0e451ff1-f835-4779-aa7c-c43e900e197b.png">

2022-02-10 05:25 UTC, anupbarve requested changes
I realised that this change will break automation.
Any prompt on terminal should also have corresponding flag on CLI to make decisions.
Example: Prompting for removal of packages should also have corresponding flag to be passed like `removeExistingPkgs`. If the flag is passed, no need to prompt, instead just make the decision based on passed value.

2022-02-21 09:21 UTC, joey00072 commented
### Added flag to ignore remove existing pkgs prompt

<img width="1314" alt="Screenshot 2022-02-21 at 2 50 02 PM" src="https://user-images.githubusercontent.com/35176826/154925390-6c0e174a-490a-4326-9592-370c99a8f53c.png">

2022-02-21 12:26 UTC, anupbarve requested changes

2022-02-21 12:26 UTC, anupbarve commented on cmd/bootstrap.go
> +		result, err := pmk.CheckNode(*cfg, c, auth, bootConfig, removeExistingPkgs)
see if you can fold the flag `removeExistingPkgs` in config structure.
Passing every new added flag via function params is a pain and should be avoided as much as possible.

2022-02-22 09:51 UTC, anupbarve approved these changes
lgtm
Please do an end-to-end testing and also get approval from @devidask27

2022-02-23 05:27 UTC, devidask27 commented
@joey00072 Please post the all the latest testing screenshots for all the possible positive and negative test cases.

2022-02-23 05:33 UTC, devidask27 commented
@joey00072 Also test the other functionalities for authorize-node, deauthorize-node, looks like this files also changed because of conflicts. so just test the functionality of that changes as well.

2022-02-23 05:55 UTC, devidask27 commented
@joey00072 By looking at the code, it looks it is not handling the case where the node is partially onboarded and we enter no when it ask for do you want to remove existing installation. I think instead of asking user to enter yes or no we should directly remove the existing installation if user is re-running the prep-node. CC: @anupbarve

2022-02-24 05:15 UTC, joey00072 commented
> @joey00072 By looking at the code, it looks it is not handling the case where the node is partially onboarded and we enter no when it ask for do you want to remove existing installation. I think instead of asking user to enter yes or no we should directly remove the existing installation if user is re-running the prep-node. CC: @anupbarve

Shouldn't we ask for user permission before deleting the packages from host machine? 
@devidask27 @anupbarve

2022-02-24 10:37 UTC, joey00072 commented
### Ubuntu

#### prep-node no
<img width="1439" alt="ubuntu-prep-node-no" src="https://user-images.githubusercontent.com/35176826/155501224-be9b5461-3908-46c6-9466-0664527f6e79.png">

#### prep-node yes
<img width="1435" alt="ubuntu-prep-node-yes" src="https://user-images.githubusercontent.com/35176826/155501129-6f5dffa4-19a8-4f4a-9ef9-2be63deb6120.png">

#### prep-node with flag
<img width="1423" alt="ubuntu-prep-node-with-flag" src="https://user-images.githubusercontent.com/35176826/155501352-eb6dae85-18e7-460d-a8f4-b27fbb6d3b90.png">

#### check-node no
<img width="1324" alt="ubuntu-check-node-no" src="https://user-images.githubusercontent.com/35176826/155501852-5f7ec3d7-0242-4fb3-a5a5-f011efb59654.png">


#### check-node yes
<img width="1423" alt="ubuntu-check-node-yes" src="https://user-images.githubusercontent.com/35176826/155501935-670c77a8-ef94-48a6-b898-ca07517d2e5d.png">

#### check-node with flag
<img width="1440" alt="ubuntu-check-node-with-flag" src="https://user-images.githubusercontent.com/35176826/155506180-fee6ae61-9810-4f2e-911e-2534b97b1370.png">



### Centos

#### prep-node no
<img width="1408" alt="centos-prep-node-no" src="https://user-images.githubusercontent.com/35176826/155502170-42b5006d-1539-4de4-bed7-3f18f3fe520a.png">


#### prep-node yes
<img width="1423" alt="centos-prep-node-yes_1" src="https://user-images.githubusercontent.com/35176826/155502543-ff34a838-afae-401d-b87a-ea4796b6aed3.png">
<img width="1423" alt="centos-prep-node-yes_2" src="https://user-images.githubusercontent.com/35176826/155502566-8ade88a2-28ef-486e-8933-89b29aa6eb62.png">



#### prep-node with flag
<img width="1440" alt="centos-prep-node-with-flag-1" src="https://user-images.githubusercontent.com/35176826/155502290-396cb704-a46a-4e2e-99ea-58e8bcc9245e.png">
<img width="1440" alt="centos-prep-node-with-flag-2" src="https://user-images.githubusercontent.com/35176826/155502306-e4e086f6-4da8-450f-b7ff-5e2e427b9db5.png">

#### check-node no
<img width="1440" alt="centos-check-node-no" src="https://user-images.githubusercontent.com/35176826/155502606-4706e3b9-e098-41cd-aae3-f90fc0df3a3f.png">



#### check-node yes
<img width="1440" alt="centos-check-node-yes-1" src="https://user-images.githubusercontent.com/35176826/155502659-9c1da337-577a-43e6-aa4b-d27c2a5a7260.png">
<img width="1440" alt="centos-check-node-yes-2" src="https://user-images.githubusercontent.com/35176826/155502688-226f3f0a-22d8-4fc3-9103-25a8715c8b98.png">

#### check-node with flag
<img width="1440" alt="centos-check-node-with-flag-2" src="https://user-images.githubusercontent.com/35176826/155504775-2e74d5e0-f572-4b6e-a78b-4d58b6e5d4e0.png">

<img width="1440" alt="centos-check-node-with-flag-1" src="https://user-images.githubusercontent.com/35176826/155504737-28dee810-f52e-46d8-a9a0-00c6bc82d50e.png">

2022-02-25 05:33 UTC, merged