Added a pull request template
platform9/pf9ctl pull request #277
Opened 2022-02-04 10:24 UTC by yogeshj83

2022-02-04 10:48 UTC, nikhilbandi commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!--- include "Fixes #FT-XXX" if you have a relevant Jira ticket -->
We should make having a Jira issue compulsory.

2022-02-04 10:51 UTC, nikhilbandi commented on .github/PULL_REQUEST_TEMPLATE.md
> +#### Reviewers
Will doing so automatically add these names are reviewers in the PR? If yes, great. If not, we can skip this.

2022-02-04 10:51 UTC, nikhilbandi requested changes
A couple minor comments / questions.

2022-02-04 12:07 UTC, yogeshj83 commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!--- include "Fixes #FT-XXX" if you have a relevant Jira ticket -->
Enforcement via PR templates is not possible. Please take a look at this discussion:
https://github.community/t/make-pr-template-field-mandatory/203194.
The main motive behind PR templates is to have uniformity across the PRs. Maybe while reviewing if the Jira field is empty, the reviewer could reject the PR.

2022-02-04 12:09 UTC, yogeshj83 commented on .github/PULL_REQUEST_TEMPLATE.md
> +#### Reviewers
I don't think that PR templates could automatically populate the reviewer name but it does give the suggestion as you start typing the reviewer name starting with '@'.

2022-02-09 07:19 UTC, yogeshj83 commented
@nikhilbandi @anupbarve Can you review the changes?

2022-02-09 10:52 UTC, anupbarve approved these changes

2022-02-14 06:06 UTC, nikhilbandi commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!--- include "Fixes #FT-XXX" if you have a relevant Jira ticket -->
Got it.

2022-02-14 06:06 UTC, nikhilbandi commented on .github/PULL_REQUEST_TEMPLATE.md
> +#### Reviewers
OK.

2022-02-14 06:06 UTC, nikhilbandi approved these changes
Approving.

2022-02-14 06:54 UTC, merged