parity with UI
platform9/pf9ctl pull request #280
Opened 2022-02-12 15:04 UTC by devidask27

2022-03-07 06:06 UTC, anupbarve commented on pkg/qbert/qbert.go
> +		if SplitPMKversion[0] <= "1.20.11" {
Put the version in constants.go
Also document the logic as to why we are having such a condition wrt the version.

2022-03-07 06:09 UTC, anupbarve requested changes
Some generic comments before this code could be reviewed.

- Please update README.md
- Please use the bug template to raise this PR in order to give more info about this change.
- Do we need to add test cases for these changes ?
- I hope you have got all the command parameters reviewed from Anmol.

2022-03-07 06:09 UTC, anupbarve commented on pkg/qbert/qbert.go
> +		Monitoring = fmt.Sprintf(`,"monitoring":"{\"retentionTime\":\"7d\"}"`)
Why 7 days ? 
Please document the logic

2022-03-07 06:09 UTC, anupbarve commented on cmd/bootstrap.go
> +	calicoNatOutgoing        int
All these variables need to have corresponding comments.

2022-03-07 06:09 UTC, anupbarve commented on cmd/bootstrap.go
> +		}
Move all the keywords to constants.go
Examples include, but not limited to :)
... 
calico
etcd-backup
docker
... etc

2022-03-09 12:16 UTC, devidask27 commented
> Some generic comments before this code could be reviewed.
> 
> * Please update README.md
> * Please use the bug template to raise this PR in order to give more info about this change.
> * Do we need to add test cases for these changes ?
> * I hope you have got all the command parameters reviewed from Anmol.

Updated README.md
Added PR template
I think no need of test cases, added two functions but it only contains fmt.Sprintf functionality
Already given the binary to anmol to try it

2022-03-11 04:42 UTC, anupbarve commented on README.md
> +  -u, --user string                         Ssh username for the node
IMHO, user is going to get overwhelmed after looking at this list of options. 
We should provide examples of how to get a cluster bootstrapped with default options.
These examples should also be part of the usage.

2022-03-14 07:24 UTC, devidask27 commented
@anupbarve Tried to Resolve points you mentioned

- groped flags as optional and required
- added bootstrap command example in command usage message
<img width="1283" alt="Screenshot 2022-03-14 at 12 52 48 PM" src="https://user-images.githubusercontent.com/76941923/158123747-8baf120b-4d0a-41e3-9344-cafe8b175338.png">

2022-03-15 06:19 UTC, anupbarve commented on README.md
> +  pf9ctl bootstrap [flags] cluster-name, e.g: pf9ctl bootstrap testCluster --pmk-version 1.21.3-pmk.72
These versions keep getting changed. How would the user know which version to use ?

2022-03-15 06:25 UTC, devidask27 commented on README.md
> +  pf9ctl bootstrap [flags] cluster-name, e.g: pf9ctl bootstrap testCluster --pmk-version 1.21.3-pmk.72
we are fetching all versions first, if user have not passed any version or he entered wrong version then we are listing all versions and asking to select one. 
we can remove this hardcoded version and can make it `pf9ctl bootstrap testCluster --pmk-version <version>`

2022-03-15 06:43 UTC, anupbarve requested changes

2022-03-15 06:43 UTC, anupbarve commented on README.md
> +  pf9ctl bootstrap [flags] cluster-name, e.g: pf9ctl bootstrap testCluster --pmk-version 1.21.3-pmk.72
yes, please remove the hardcoded version string from here and below as well.

2022-03-15 07:03 UTC, devidask27 commented on README.md
> +  pf9ctl bootstrap [flags] cluster-name, e.g: pf9ctl bootstrap testCluster --pmk-version 1.21.3-pmk.72
Done

2022-03-15 08:03 UTC, anupbarve approved these changes

2022-03-15 08:20 UTC, merged