decommission-node remote support
platform9/pf9ctl pull request #286
Opened 2022-03-01 11:04 UTC by devidask27

## ISSUE(S):

https://platform9.atlassian.net/browse/FT-350

## SUMMARY

## ISSUE TYPE

- [x] Bug fix (non-breaking change which fixes an issue)
- [✓] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that may cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## IMPACTED FEATURES/COMPONENTS:

Impacted commands
decommission-node

## TESTING DONE

#### Manual

#### Reviewers

/cc @anupbarve @nikhilbandi

2022-03-07 06:00 UTC, anupbarve requested changes

2022-03-07 06:00 UTC, anupbarve commented on pkg/pmk/decomissionNode.go
> +		"Removing pf9 HOME dir":  "rm -rf $HOME/pf9",
Possibly use the constants from here : https://github.com/platform9/pf9ctl/blob/master/pkg/util/constants.go#L92

2022-03-07 06:00 UTC, anupbarve commented on pkg/pmk/decomissionNode.go
> +	}
Return in case of error ?

2022-03-07 06:00 UTC, anupbarve commented on pkg/pmk/decomissionNode.go
> +		"rm -rf /var/opt/pf9",
Put the list in constants.go, specifically the services and files.
You can construct the above commands i.e. pkill and rm dynamically in code using those constants.

2022-03-07 06:00 UTC, anupbarve commented on pkg/pmk/decomissionNode.go
> +			"yum erase -y pf9-muster",
Put the list in constants.go, specifically the services.
You can construct the above command i.e. `yum erase` dynamically in code using those constants.

2022-03-07 11:07 UTC, devidask27 commented on pkg/pmk/decomissionNode.go
> +		"Removing pf9 HOME dir":  "rm -rf $HOME/pf9",
Done

2022-03-07 11:07 UTC, devidask27 commented on pkg/pmk/decomissionNode.go
> +	}
Added fatalf

2022-03-07 11:07 UTC, devidask27 commented on pkg/pmk/decomissionNode.go
> +		"rm -rf /var/opt/pf9",
Done

2022-03-07 11:08 UTC, devidask27 commented on pkg/pmk/decomissionNode.go
> +			"yum erase -y pf9-muster",
Done

2022-03-09 07:18 UTC, devidask27 commented
**Testing**
**Remote decommission centos**
<img width="1088" alt="cnt1" src="https://user-images.githubusercontent.com/76941923/157390623-5c32a9a6-930c-475a-acbe-4fde62be3c39.png">
<img width="1088" alt="cnt2" src="https://user-images.githubusercontent.com/76941923/157390684-ece4c194-8697-479b-8371-0cf2ba3f8d96.png">
<img width="1088" alt="cnt3" src="https://user-images.githubusercontent.com/76941923/157390741-08dcc7b2-e5ee-4649-bbcc-52c914a8c37d.png">
<img width="1088" alt="cnt4" src="https://user-images.githubusercontent.com/76941923/157390812-d789c6f6-e674-4993-a29e-35975924b2b0.png">

**Remote decommission ubuntu**
<img width="1088" alt="ub1" src="https://user-images.githubusercontent.com/76941923/157390942-1ca93dc7-5f98-4a76-9171-d4ead921b826.png">
<img width="1088" alt="ub2" src="https://user-images.githubusercontent.com/76941923/157391143-ce0ad90f-5fe6-42ef-92e7-749058e6c3b5.png">
<img width="1088" alt="ub3" src="https://user-images.githubusercontent.com/76941923/157391231-dfe87971-0b95-440e-97fc-64ff71f368f8.png">

**Local decommission ubuntu**
<img width="1088" alt="lc1" src="https://user-images.githubusercontent.com/76941923/157391375-b305e7d2-1af1-4ed2-9c95-669c373fc694.png">
<img width="1088" alt="lc2" src="https://user-images.githubusercontent.com/76941923/157391465-04ef9008-57d5-47af-b339-c41d7dc17487.png">
<img width="1088" alt="lc3" src="https://user-images.githubusercontent.com/76941923/157391519-20837d2a-30ce-4ee0-9ab5-04560a254155.png">

2022-03-11 04:30 UTC, anupbarve submitted a review, later dismissed
lgtm

2022-03-11 04:30 UTC, anupbarve commented on pkg/cmdexec/executor.go
> +	//fmt.Println(strings.TrimSpace(o))
remove.

2022-03-11 04:36 UTC, anupbarve commented
we should re-think on what is being displayed on console. It is mostly garbage from user's perspective. Maybe open another jira to clean it up.

2022-03-11 06:03 UTC, anupbarve approved these changes

2022-03-11 06:05 UTC, merged