added flag to pass log-location and also logged the console messages into log file
platform9/pf9ctl pull request #291
Opened 2022-03-28 07:46 UTC by devidask27

## ISSUE(S):

https://platform9.atlassian.net/browse/FT-262

## SUMMARY

Added new flag to pass location to save logs, and also logged the console messages into logfile

## ISSUE TYPE

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that may cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## RELATED ISSUE(S):

https://platform9.atlassian.net/browse/FT-361

## TESTING DONE
#### Manual

**Flag to pass log location**
<img width="811" alt="Screenshot 2022-03-28 at 12 57 48 PM" src="https://user-images.githubusercontent.com/76941923/160350445-3b6f8ba0-02ce-4c43-9485-628ebabb22bc.png">
**User defined log location to save logs**
<img width="1365" alt="Screenshot 2022-03-28 at 12 59 21 PM" src="https://user-images.githubusercontent.com/76941923/160350550-bf5eb850-3793-47b0-a926-9b911fffba03.png">
**Default log location**
<img width="1373" alt="Screenshot 2022-03-28 at 1 02 07 PM" src="https://user-images.githubusercontent.com/76941923/160350659-452a76d2-8013-4e33-8313-25c95fe3350c.png">

#### Reviewers

2022-03-28 10:03 UTC, devidask27 commented
Log file
[pf9ctl-20220328.log](https://github.com/platform9/pf9ctl/files/8361663/pf9ctl-20220328.log)

2022-03-31 03:51 UTC, anupbarve requested changes

2022-03-31 03:51 UTC, anupbarve commented on cmd/root.go
> +	} else {
What happens when the logDirPath doesn't exist ?
The directory should be created with appropriate permissions.

2022-03-31 03:51 UTC, anupbarve commented on cmd/root.go
> +		util.Pf9LogLoc = "pf9/log"
Add to constants.

2022-03-31 03:51 UTC, anupbarve commented on pkg/util/constants.go
> +	Pf9LogLoc string
why ?

2022-04-04 05:09 UTC, devidask27 commented on cmd/root.go
> +	} else {
if the logDirPath doesn't exist then it throughs error with message no such file or directory
<img width="906" alt="Screenshot 2022-04-04 at 10 37 32 AM" src="https://user-images.githubusercontent.com/76941923/161477549-42d3d33d-ced5-49e2-bbdc-f44d2ec3b029.png">

2022-04-04 05:12 UTC, devidask27 commented on pkg/util/constants.go
> +	Pf9LogLoc string
Previously default log locations was "pf9/log" but now its depends on user so assigning value based on flag.

2022-04-04 05:29 UTC, devidask27 commented on cmd/root.go
> +		util.Pf9LogLoc = "pf9/log"
Done

2022-04-06 11:37 UTC, anupbarve commented on cmd/root.go
> +	} else {
We need to create the directory via code as mentioned above instead of erroring out.

2022-04-07 09:37 UTC, anupbarve approved these changes

2022-04-07 09:42 UTC, merged