changed the decommission steps as per documentation
platform9/pf9ctl pull request #293
Opened 2022-04-06 04:59 UTC by devidask27

## ISSUE(S):

https://platform9.atlassian.net/browse/FT-374
## SUMMARY

- Decommission node steps was not as per the documentation so changed it as per documentation.
- Fixed bug where packages was not getting removed in case of partially onboarded node

## ISSUE TYPE

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that may cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## IMPACTED FEATURES/COMPONENTS:

Impacted command
decommission-node

## RELATED ISSUE(S):

https://platform9.atlassian.net/browse/FT-364

## TESTING DONE

#### Manual

**decommission on ubuntu local**
<img width="727" alt="Screenshot 2022-04-05 at 5 55 00 PM" src="https://user-images.githubusercontent.com/76941923/161897717-f35dcff0-4066-42bc-b35b-786f6be25f4a.png">
**decommission on centos local**
<img width="727" alt="Screenshot 2022-04-05 at 6 03 50 PM" src="https://user-images.githubusercontent.com/76941923/161897820-4818989c-5df0-4c2e-9806-4ff7ce345ef6.png">
**decommission on centos remote**
<img width="727" alt="Screenshot 2022-04-05 at 5 37 32 PM" src="https://user-images.githubusercontent.com/76941923/161898044-8fa91170-c128-43b3-ad88-f09ebfa1fc9e.png">
**decommission on ubuntu remote**
<img width="727" alt="Screenshot 2022-04-05 at 4 00 00 PM" src="https://user-images.githubusercontent.com/76941923/161898181-bdaa7d15-3c06-4889-8876-9a4ee4212bd2.png">
**decommission on node which is connected to cluster**
<img width="727" alt="Screenshot 2022-04-05 at 5 48 34 PM" src="https://user-images.githubusercontent.com/76941923/161898264-445efa9c-7b73-4ff8-a7de-dca0c2e05b81.png">
**decommission on node which is not connected to DU but host agent is installed (partial)**
<img width="727" alt="Screenshot 2022-04-05 at 6 08 54 PM" src="https://user-images.githubusercontent.com/76941923/161898475-e6c961b3-58f9-4ed1-bf5a-08bff62e898e.png">
**prep-node on node which is partially onboarded (not connected to DU but hostagent is installed)**
<img width="673" alt="Screenshot 2022-04-06 at 10 00 44 AM" src="https://user-images.githubusercontent.com/76941923/161898663-50b2233c-726f-4c39-9515-076d86126230.png">
**decommission on fresh vm ubuntu**
<img width="727" alt="Screenshot 2022-04-05 at 6 10 15 PM" src="https://user-images.githubusercontent.com/76941923/161898763-e0753a52-065f-4aa2-a1b9-1e360c6a485e.png">
**decommission on fresh vm centos**
<img width="727" alt="Screenshot 2022-04-05 at 6 11 20 PM" src="https://user-images.githubusercontent.com/76941923/161898824-bdc51e83-e8be-4d65-b233-740cce6cb2fa.png">

#### Reviewers

/cc @anupbarve @nikhilbandi

2022-04-07 11:08 UTC, anupbarve requested changes

2022-04-07 11:08 UTC, anupbarve commented on pkg/pmk/decomissionNode.go
> +				removePf9Instation(c)
%s/Instation/Installation

2022-04-07 11:08 UTC, anupbarve commented on pkg/pmk/decomissionNode.go
> +				removeHostagent(c, hostOS)
Can be taken outside the if-else condition.

2022-04-11 05:10 UTC, devidask27 commented on pkg/pmk/decomissionNode.go
> +				removeHostagent(c, hostOS)
If we take it outside then it will be get called twice.

2022-04-11 05:10 UTC, devidask27 commented on pkg/pmk/decomissionNode.go
> +				removePf9Instation(c)
Done

2022-04-11 05:10 UTC, devidask27 commented on pkg/pmk/decomissionNode.go
> +		_, err = c.Executor.RunWithStdout("bash", "-c", "dpkg -l | grep hostagent")
Done

2022-04-11 05:29 UTC, anupbarve approved these changes

2022-04-11 05:31 UTC, merged