Private/shubhamc/cli dpkg lock check failed ft 336
platform9/pf9ctl pull request #296
Opened 2022-04-18 04:06 UTC by joey00072

## ISSUE(S):

CLI dpkg lock check failed. Because  of unattended-upgrades
[FT-366](https://platform9.atlassian.net/browse/FT-366)

## SUMMARY

If unattended-upgrades start after dpkg lock check in check-node.
dpkg would go under lock and we would unable to install hostagent.

Added additional dpkg lock check after stoping unattended-upgrades.
Also add check if unattended-upgrades is disabled by default.

## ISSUE TYPE

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that may cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## IMPACTED FEATURES/COMPONENTS:

changed debian.checkIfdpkgISLock to debian.CheckIfdpkgISLock to use outside debian package

## TESTING DONE
#### Automated

#### Manual

#### If unattended-upgrades starts running before check-node
<img width="1440" alt="Screenshot 2022-04-11 at 2 50 28 PM" src="https://user-images.githubusercontent.com/35176826/163370311-db26ec05-9dc2-4951-bfc2-4b3ce1935b98.png">

#### If unattended-upgrades starts running after check-node
<img width="1349" alt="Screenshot 2022-04-11 at 3 59 42 PM" src="https://user-images.githubusercontent.com/35176826/163752688-b1f14de1-33c3-4124-95a8-cc7348270f63.png">

#### If unattended-upgrades active but not running yet
<img width="1349" alt="Screenshot 2022-04-14 at 12 18 36 PM" src="https://user-images.githubusercontent.com/35176826/163752728-b1c1dcca-3bca-4dbf-855d-19177238fcbf.png">

#### Reviewers
@devidask27 @AnirudhPokala @anupbarve @yogeshj83

2022-04-26 02:37 UTC, joey00072 commented
#### When dpkg locked by unattended-upgrade
<img width="1391" alt="Screenshot 2022-04-25 at 4 37 04 PM" src="https://user-images.githubusercontent.com/35176826/165208278-5b99e1ec-5be4-4242-aa52-fd39fb385628.png">

#### When dpkg lock by apt
<img width="1391" alt="Screenshot 2022-04-25 at 4 37 42 PM" src="https://user-images.githubusercontent.com/35176826/165208285-948dfb70-7bcc-40c9-bfa7-d4adc8020f0b.png">

2022-04-26 04:39 UTC, devidask27 requested changes

2022-04-26 04:39 UTC, devidask27 commented on pkg/pmk/node.go
> +	platform := debian.NewDebian(allClients.Executor)
I think this will fail in case of centos. this should be called if and only if host os is debian.

2022-04-26 05:07 UTC, joey00072 commented on pkg/pmk/node.go
> +	platform := debian.NewDebian(allClients.Executor)
Fixed 👍

2022-04-27 05:09 UTC, devidask27 submitted a review, later dismissed
Looks good.

2022-04-27 10:57 UTC, anupbarve commented on pkg/platform/debian/debian.go
> +			return false, fmt.Errorf(fmt.Sprintf("Unable to acquire the dpkg - %s", output))
Isn't there a race condition where lock was acquired but got released and you try to print the process ID, but fail. This will fail the entire operation ?

2022-04-28 08:33 UTC, joey00072 commented on pkg/platform/debian/debian.go
> +			return false, fmt.Errorf(fmt.Sprintf("Unable to acquire the dpkg - %s", output))
<img width="1391" alt="Screenshot 2022-04-28 at 2 00 50 PM" src="https://user-images.githubusercontent.com/35176826/165711609-6bf0ba33-fdd8-4264-b204-6859d4dac86a.png">

No In that case it will just return empty string and output will be like this

2022-04-28 08:33 UTC, joey00072 commented on pkg/pmk/node.go
> +	output, err := allClients.Executor.RunWithStdout("bash", "-c", "systemctl status unattended-upgrades | grep -i Active")
Done 👍

2022-04-29 04:29 UTC, anupbarve approved these changes

2022-04-29 04:50 UTC, merged