Private/devidas/spec based config
platform9/pf9ctl pull request #304
Opened 2022-05-06 05:19 UTC by devidask27

## ISSUE(S):

## SUMMARY

## ISSUE TYPE

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that may cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## IMPACTED FEATURES/COMPONENTS:

## RELATED ISSUE(S):

## DEPENDS ON:

## TESTING DONE
#### Automated

#### Manual

#### Reviewers

2022-05-17 05:07 UTC, anupbarve requested changes

2022-05-17 05:07 UTC, anupbarve commented on pkg/config/config.go
> +		fmt.Println("Error opening node config file")
return in case of error?

2022-05-17 05:07 UTC, anupbarve commented on pkg/config/configCreate.go
> +		fmt.Println("Error creating config file, please try again")
return in case of error

2022-05-17 05:07 UTC, anupbarve commented on cmd/createConfig.go
> +				} else {
aren't all the structures in `objects.go` supporting yaml only ? Would they work for json ?

2022-05-17 06:13 UTC, devidask27 commented on cmd/bootstrap.go
> +	//cfg := &objects.UserData{OtherData: objects.Other{WaitPeriod: time.Duration(60), AllowInsecure: false}, MfaToken: bootConfig.MFA}
I have commented it because it was replicated unnecessarily. it is declared in cmd/config.go file.

2022-05-17 06:14 UTC, devidask27 commented on cmd/bootstrap.go
> +	//cfg := &objects.UserData{OtherData: objects.Other{WaitPeriod: time.Duration(60), AllowInsecure: false}, MfaToken: bootConfig.MFA}
I will remove that commented line.

2022-05-17 06:24 UTC, devidask27 commented on pkg/pmk/checkNode.go
> -		if !nc.RemoveExistingPkgs {
yes it is further passed to another function (DecommissionNode) from this (checkNode) function

2022-05-17 06:26 UTC, devidask27 commented on pkg/util/constants.go
> +		fmt.Println("updated config location: ", Pf9DBLoc)
No, removed

2022-05-17 06:27 UTC, devidask27 commented on pkg/objects/objects.go
> +	Region   string `json:"region"`
sure

2022-05-17 07:24 UTC, devidask27 commented on pkg/config/config.go
> +		fmt.Println("Error opening node config file")
No need i think, it will print error on console if it fails to open it.

2022-05-17 07:54 UTC, devidask27 commented on pkg/config/configCreate.go
> +		fmt.Println("Error creating config file, please try again")
Okay. will do

2022-05-18 10:00 UTC, devidask27 commented on cmd/createConfig.go
> +				} else {
yes will work for both now changed the logic

2022-05-19 05:55 UTC, anupbarve approved these changes

2022-05-19 06:36 UTC, devidask27 commented
merged this into pf9ctl-2.0 branch. so closing this one.

2022-05-19 06:36 UTC, closed without merging