Add option to skip node auth in prep-node
platform9/pf9ctl pull request #315
Opened 2022-06-30 18:34 UTC by pacharya-pf9

## ISSUE(S):

## SUMMARY

PMK CAPI uses `pf9ctl prep-node` command in boot script of all instances. However pf9ctl always pushes the latest version to a node. This conflicts with the version being pushed by controller-manager. Although eventually the version pushed by controller-manager is one installed on the host, this process is delayed because pf9-kube package is downloaded, installed and removed at least couple of times.

This commits adds a new hidden option to NOT install pf9-kube role as part of the prep-node command. This hidden option will be used in the PMK CAPI project to remove the race condition since only one component i.e. controller-manager will push/remove the pf9-kube role from the host in case it is CAPI-managed.

## ISSUE TYPE

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that may cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## IMPACTED FEATURES/COMPONENTS:

## RELATED ISSUE(S):

https://github.com/platform9/pf9-cluster-api/pull/137
https://github.com/platform9/pf9-qbert/pull/1348

## DEPENDS ON:

## TESTING DONE
#### Automated

#### Manual

#### Reviewers

2022-07-01 05:32 UTC, devidask27 requested changes

2022-07-01 05:32 UTC, devidask27 commented on cmd/prepNode.go
> +	skipKube       bool = false
We can either make this exportable or we can put into constants.go (in util pkg). so that we don't need to change (pass one more value to prepNode function) definition of prepNode function.

2022-07-01 19:28 UTC, pacharya-pf9 commented on cmd/prepNode.go
> +	skipKube       bool = false
Done.

2022-07-05 21:02 UTC, erwinvaneyk approved these changes
Minor comment, lgtm in any case

2022-07-05 21:02 UTC, erwinvaneyk commented on cmd/prepNode.go
> +	skipKube       bool = false
The `false` is not really needed

2022-07-05 21:02 UTC, erwinvaneyk commented on pkg/pmk/node.go
> +		zap.S().Debug("Skip authorizing host as --skip-kube flag is true")
Wouldn't it be more fitting to call this `--skip-auth`?

2022-07-06 01:59 UTC, pacharya-pf9 commented on pkg/pmk/node.go
> +		zap.S().Debug("Skip authorizing host as --skip-kube flag is true")
I intentionally kept it as --skip-kube as I don't want kube role to be installed. However if in future we add support for pushing aka authorizing other roles e.g. pf9-support then that would be out of scope of this flag.

2022-07-06 02:01 UTC, pacharya-pf9 commented on cmd/prepNode.go
> +	skipKube       bool = false
Yeah... I was trying to be explicit... Dropped that `= false`

2022-07-06 02:01 UTC, pacharya-pf9 commented on cmd/prepNode.go
> +	prepNodeCmd.Flags().BoolVarP(&util.SkipKube, "skip-kube", "", false, "Skip installing pf9-kube/nodelet on this host")
done

2022-07-06 04:05 UTC, devidask27 approved these changes
lgtm

2022-07-06 04:58 UTC, merged