check-node command
platform9/pf9ctl pull request #36
Opened 2021-01-12 04:53 UTC by sahil-lakhwani

Signed-off-by: sahil-lakhwani <sahilakhwani@gmail.com>

Adds a new sub-command to check if a VM meets the prerequisites to be registered as a Kubernetes node.

2021-01-12 12:12 UTC, anupbarve reviewed
I would like to avoid parsing output from the commands run using the executor (if possible).
Could you please check if we can use existing golang libraries ?
Parsing the stdout is painful and should be avoided as far as possible.
I am not sure if the existing libraries would be helpful on remote nodes though. If that is the case, then we can go ahead with the current way of implementation.

2021-01-12 12:12 UTC, anupbarve commented on pkg/pmk/checkNode.go
> +	cpuS, err := exec.RunWithStdout("bash", "-c", "grep -c ^processor /proc/cpuinfo | tr -d '\\n'")
Can we use https://golang.org/pkg/internal/cpu/ instead.

2021-01-12 12:12 UTC, anupbarve commented on pkg/pmk/checkNode.go
> +	memS, err := exec.RunWithStdout("bash", "-c", "echo $(($(getconf _PHYS_PAGES) * $(getconf PAGE_SIZE) / (1024 * 1024))) | tr -d '\\n'")
Can we use package like https://godoc.org/github.com/artyom/meminfo instead ?

2021-01-12 12:12 UTC, anupbarve commented on pkg/pmk/checkNode.go
> +	diskS, err := exec.RunWithStdout("bash", "-c", "df -k . --output=size | sed 1d | xargs | tr -d '\\n'")
can we use pkg like https://godoc.org/github.com/gyuho/linux-inspect/df instead ?

2021-01-12 12:12 UTC, anupbarve commented on pkg/pmk/checkNode.go
> +	openPorts, err := exec.RunWithStdout("bash", "-c", "netstat -tupna | awk '{print $4}' | sed -e 's/.*://' | sort | uniq")
could we use net lib to do this ?

2021-01-12 12:22 UTC, anupbarve commented on pkg/util/slices.go
> +func Intersect(a interface{}, b interface{}) []interface{} {
Please add documentation to the functions in this file. These being in utils, need to be easily usable by others.

2021-01-13 18:55 UTC, raghuP9 requested changes
Added few comments. PTAL

2021-01-13 18:55 UTC, raghuP9 commented on pkg/pmk/checkNode.go
> +	os, err := validatePlatform(exec)
This is hardcoded because we want a fix set of distributions to be supported via CLI. We can move the patterns out into constants. But any support for new platform will require code change, followed by binary generation.

2021-01-13 18:55 UTC, raghuP9 commented on pkg/pmk/checkNode.go
> +type packagesCheck struct{}
Don't add separate structs for each check in this file. Add distribution specific packages and add these methods corresponding to them as part of interface implementation or else each of these methods will morph into massive if else and switches as we keep on adding new distributions and releases.

e.g.
```
// pkg/platforms/debian/debian.go

func (plat *Debian) checkMem() (bool, error) {}

--------------------------------------------------
// pkg/platforms/centos/centos.go

func (plat *Centos) checkMem() (bool, error) {}
```

This way, you can use distribution specific bundled tools that come with OS instead of trying to find common set of commands and utilities.

Also whenever you'll add support for new distributions, you'll just have to implement the interface in a new file specific to that new distribution. This will avoid adding massive code changes in existing libraries and in turn reduce regressions.

2021-01-14 07:41 UTC, sahil-lakhwani commented
> I would like to avoid parsing output from the commands run using the executor (if possible).
> Could you please check if we can use existing golang libraries ?
> Parsing the stdout is painful and should be avoided as far as possible.
> I am not sure if the existing libraries would be helpful on remote nodes though. If that is the case, then we can go ahead with the current way of implementation.

Yes, for remote nodes, the current code executes bash commands via a SSH client. This helps in a way that same commands are run for both local and remote nodes.  I think we can keep this until we have a better approach.

2021-01-14 11:48 UTC, sahil-lakhwani commented on pkg/pmk/checkNode.go
> +type packagesCheck struct{}
I think most the checks are same for all Linux distros. I like the idea of making platform specific implementations but that may result in duplication of code.
What I think we could do is have this checks in chain and call platform specific code only when needed (with proper interface and implementations)

Thoughts?

2021-01-14 16:22 UTC, raghuP9 commented on pkg/pmk/checkNode.go
> +type packagesCheck struct{}
That is an assumption that most checks will always be the same. We cannot predict default packages change from vendors and then in future convolute the single codebase which in turn makes unit and functional testing of different code paths hard.

Default executable paths vary as well on different platforms so you'll end up writing the platform specific functions in a single package which could have been part of that platform module anyway. There is some duplication but it is much more maintainable in the long run. That is the very reason behind interface pattern where you can write independent implementations, extend functionality without worrying about introducing regressions to other modules.

You are also assuming that there is going to be same set of checks for all platforms. In container world, things change rapidly with the help of active community. Committing ourselves to this assumption limits our product maintenance and extendibility.

2021-01-15 09:01 UTC, sahil-lakhwani commented on pkg/pmk/checkNode.go
> +type packagesCheck struct{}
If the set of checks are not same for all the platforms, then I am thinking if an interface like one mentioned above will be satisfied by all the platform specific implementations.

Also that is why I am trying to have mix of both of approaches - abstracting out common implementations (like default methods in abstract classes)
cc: @anupbarve

2021-01-15 09:18 UTC, raghuP9 commented on pkg/pmk/checkNode.go
> +type packagesCheck struct{}
```
// pkg/platforms/debian/debian.go
package debian

type Debian struct {}

func (plat *Debian) Check() (errs []error) {

  if err := checkDebianPlat1(); err != nil {
    errs := append(errs, err)
  }

  if err := checkDebianPlat2(); err != nil {
    errs := append(errs, err)
  }

  ...
    if err := checkDebianPlatN(); err != nil {
    errs := append(errs, err)
  }

  return
}

func (plat *Debian) checkDebainPlat1() error {}
func (plat *Debian) checkDebainPlat2() error {}
func (plat *Debian) checkDebainPlat3() error {}
...
func (plat *Debian) checkDebainPlatN() error {}

--------------------------------------------------
// pkg/platforms/centos/centos.go
package centos

type Centos struct {}

func (plat *Centos) Check() (errs []error) {

  if err := checkCentosPlat1(); err != nil {
    errs := append(errs, err)
  }

  if err := checkCentosPlat2(); err != nil {
    errs := append(errs, err)
  }

  ...
    if err := checkCentosPlatN(); err != nil {
    errs := append(errs, err)
  }

  return
}

func (plat *Debian) checkCentosPlat1() error {}
func (plat *Debian) checkCentosPlat2() error {}
func (plat *Debian) checkCentosPlat3() error {}
...
func (plat *Debian) checkCentosPlatN() error {}

--------------------------------------------------
// pkg/pmk/Node.go
package node

type Platform interface {
  Check() []error
}

type Node struct {
  platform Platform
}

func NewNode() *Node {
  // check Platform using /etc/os-release file
  // then create platform specific struct
  // such as Debian{} or Centos{}

  // return &Node{Debian{}} or &Node{Cenots{}}
}

func (n *Node) Check() []errors {
  return n.platform.Check()
}
```

2021-01-15 09:22 UTC, raghuP9 commented on cmd/checkNode.go
> +// Copyright © 2020 The pf9ctl authors
```suggestion
// Copyright © 2020 The Platform9 Systems Inc.
```

2021-01-15 11:05 UTC, anupbarve commented on pkg/pmk/checkNode.go
> +type packagesCheck struct{}
@sahil-lakhwani 
If your concern is about code duplication, IMO, it will be minor.
+1 for having distribution specific packages.

2021-01-21 12:23 UTC, raghuP9 commented
@sahil-lakhwani Will you adding any unit test cases to this PR?

2021-01-21 12:31 UTC, sahil-lakhwani commented
> @sahil-lakhwani Will you be adding any unit test cases to this PR?

We'll take it in a different PR, we're deciding on a testing framework for the complete project.

Also, a note on the licensing comment -  I am not sure why that is showing as resolved - but I'll have a different PR for that too, because there are are many files which have at least 2 different license headers. So will make sure to make it uniform across.

2021-01-22 08:27 UTC, anupbarve approved these changes
Please put the console output in the description for our records.

LGTM

2021-01-25 11:15 UTC, sahil-lakhwani commented
hey @raghuP9 does this look good to you?

2021-01-26 17:30 UTC, raghuP9 commented
> hey @raghuP9 does this look good to you?
Yes, can you create a JIRA ticket for unit test and post the link here?

2021-01-27 05:38 UTC, sahil-lakhwani commented
> > hey @raghuP9 does this look good to you?
> > Yes, can you create a JIRA ticket for unit test and post the link here?

This is the ticket: https://platform9.atlassian.net/browse/FT-12

2021-01-27 08:31 UTC, anupbarve commented
> > > hey @raghuP9 does this look good to you?
> > > Yes, can you create a JIRA ticket for unit test and post the link here?
> 
> This is the ticket: https://platform9.atlassian.net/browse/FT-12

Above Jira will be treated as an umbrella ticket for all the testing.
@raghuP9 The merge is blocked since you have requested changes. Could you please unblock it ?

2021-01-27 09:27 UTC, raghuP9 approved these changes

2021-01-27 12:16 UTC, merged