Update go mod version
platform9/pf9ctl pull request #384
Opened 2024-08-08 07:50 UTC by vedantjoshi84

2024-08-12 18:20 UTC, cruizen requested changes
Hi @vedantjoshi84 , I was talking to @mithilarun  that the `make build` target looks right with the additional ldflags but we somehow still don't have a statically linked executable. He brought to my notice that the Teamcity build calls the script `build.bash` that calls the target `make container-build`. This target uses `golang:1.18` and more importantly doesn't use the same flags (`CGO_ENABLED=0` and the ldflags added recently).

2024-08-30 17:30 UTC, cruizen requested changes

2024-08-30 17:30 UTC, cruizen commented on Makefile
> +	docker run --rm --env XDG_CACHE_HOME=$(XDG_CACHE_HOME) --env SEGMENT_KEY_PRD_PMKFT=$(SEGMENT_KEY_PRD_PMKFT) --env VERSION_OVERRIDE=${VERSION_OVERRIDE} --env GOPATH=/tmp --env GOFLAGS=$(GOFLAGS) --us
```suggestion
	docker run --rm --env XDG_CACHE_HOME=$(XDG_CACHE_HOME) --env SEGMENT_KEY_PRD_PMKFT=$(SEGMENT_KEY_PRD_PMKFT) --env VERSION_OVERRIDE=${VERSION_OVERRIDE} --env GOPATH=/tmp --env GOFLAGS=$(GOFLAGS) --user $(CONT_USER):$(CONT_GRP) --volume $(PWD):$(PACKAGE_GOPATH) $(GIT_STORAGE_MOUNT) --workdir $(PACKAGE_GOPATH) golang:1.18 make ldflags="-s -w -extldflags '-static'"
```

2024-08-30 17:30 UTC, cruizen commented on Makefile
> +	docker run --rm --env XDG_CACHE_HOME=$(XDG_CACHE_HOME) --env SEGMENT_KEY_PRD_PMKFT=$(SEGMENT_KEY_PRD_PMKFT) --env VERSION_OVERRIDE=${VERSION_OVERRIDE} --env GOPATH=/tmp --env GOFLAGS=$(GOFLAGS) --us
`LDFLAGS` is lowercase in the build target. Uppercase here.

2024-09-13 15:54 UTC, mithilarun approved these changes

2024-09-14 10:41 UTC, cruizen commented on Makefile
> +	docker run --rm --env XDG_CACHE_HOME=$(XDG_CACHE_HOME) --env SEGMENT_KEY_PRD_PMKFT=$(SEGMENT_KEY_PRD_PMKFT) --env VERSION_OVERRIDE=${VERSION_OVERRIDE} --env GOPATH=/tmp --env GOFLAGS=$(GOFLAGS) --us
Can you pass ldflags

2024-09-14 10:47 UTC, cruizen reviewed
Suggested a change in `container-build`

2024-10-14 06:05 UTC, merged