Centos test
platform9/pf9ctl pull request #41
Opened 2021-02-02 03:52 UTC by devidask27

Test cases added for prerequisite check for check-node for both versions Centos and Debian

2021-02-03 11:02 UTC, sahil-lakhwani requested changes
I think we can also write tests the `err` field in the  `want` struct. For this, have the executor return an error.

2021-02-03 11:54 UTC, anupbarve commented on pkg/platform/centos/centos_test.go
> +						return "1", nil
Could you please state as to why this should fail ?
From reading the test case, we wouldn't know what are success and failure conditions.
Put appropriate comments for both success and failure conditions.

This applies to all the test cases.

2021-02-03 11:55 UTC, anupbarve commented
Also run a TC build with your branch and post the TC build link here.

2021-02-04 04:20 UTC, devidask27 commented on pkg/platform/centos/centos_test.go
> +						return "1", nil
Sure i will do it.

2021-02-04 05:51 UTC, devidask27 commented on pkg/platform/centos/centos_test.go
> +func TestPort(t *testing.T) {
Tested with mixed output

2021-02-04 05:51 UTC, devidask27 commented on pkg/platform/centos/centos_test.go
> +						return "1", nil
Added comments for each test case

2021-02-05 12:58 UTC, anupbarve requested changes
Could you please also add test cases for `removePyCli` functionality.

2021-02-05 12:58 UTC, anupbarve commented on pkg/platform/centos/centos_test.go
> +		//Returning 4 CPUS. Therfore test case should pass
nit: Therfore spelling here and everywhere.

2021-02-10 07:18 UTC, closed without merging