check and remove python cli components
platform9/pf9ctl pull request #42
Opened 2021-02-02 11:46 UTC by sahil-lakhwani

Signed-off-by: sahil-lakhwani <sahilakhwani@gmail.com>

Checks if the any of the Python CLI components are present on the machine and removes them.

2021-02-02 12:12 UTC, anupbarve requested changes
Shouldn't these be integrated in check-node and prep-node flow ?

2021-02-02 14:28 UTC, anupbarve commented
`checkPyCli` is not called in `Check` function. Am I missing something ?

2021-02-02 14:42 UTC, sahil-lakhwani commented
> `checkPyCli` is not called in `Check` function. Am I missing something ?

yeah my bad @anupbarve . Some check-in issue I believe, have pushed a new commit.

2021-02-02 15:21 UTC, anupbarve submitted a review, later dismissed
nit to be addressed.
Rest looks good.
LGTM

2021-02-02 15:21 UTC, anupbarve commented on pkg/platform/centos/centos.go
> +func (c *CentOS) checkPyCli() (bool, error) {
`checkPyCli` seems misnomer here. 
Maybe use `erasePyCli` or `removePyCli`.

2021-02-03 06:26 UTC, anupbarve approved these changes

2021-02-03 06:26 UTC, merged