Private/devidask/prep node testing
platform9/pf9ctl pull request #58
Opened 2021-02-11 07:20 UTC by devidask27

Added prep-node test cases

1. load config
2. setup node
3. get executor

2021-02-11 07:24 UTC, devidask27 commented
TC build link 
http://teamcity.platform9.horse:8111/buildConfiguration/Pf9project_Platform9Components_Pf9ctl/1429929

2021-02-11 08:08 UTC, nikhilbandi commented on pkg/pmk/config_test.go
> +				err : fmt.Errorf("Config absent, run `sudo pf9ctl config set`"),
A better message might be, "Configuration details not provided, run ....."

2021-02-11 08:09 UTC, nikhilbandi commented on pkg/pmk/config_test.go
> +	tmpFile, err := ioutil.TempFile("/tmp","config.json")
Should this path be provided in a config file from which it could be referred?

2021-02-11 08:10 UTC, nikhilbandi commented on pkg/pmk/config_test.go
> +		t.Errorf("Error creating a tempfile %s", err)
Better error message might be, "Error creating temporary file. ...."

2021-02-12 06:03 UTC, devidask27 commented on pkg/pmk/config_test.go
> +	tmpFile, err := ioutil.TempFile("/tmp","config.json")
I think that is not required because we are just faking it in order to test the function

2021-02-22 12:25 UTC, devidask27 commented
TC build link
http://teamcity.platform9.horse:8111/buildConfiguration/Pf9project_Platform9Components_Pf9ctl/1441137

2021-02-22 13:32 UTC, sahil-lakhwani requested changes
- Please add a new line at end of every file
 - Any reason for specifically using assert.Equal instead of cmp.Diff  wherever possible - just to keep uniform code across

2021-02-22 13:32 UTC, sahil-lakhwani commented on pkg/pmk/clients_test.go
> +		})
Should there be a failure case here?

Also, can you check if the `client` as a whole can be compared instead of individual fields in the struct .

2021-02-23 07:25 UTC, devidask27 commented on pkg/pmk/clients_test.go
> +		})
- cmp.Diff gives error while comparing for error thats why i used assert.Equal
- and client structure have multiple structures thats why i compared each structure separately
- and i think currently new client function  not having failure case. because every time it returns nil error

2021-02-23 11:36 UTC, devidask27 commented
TC build link
http://teamcity.platform9.horse:8111/buildConfiguration/Pf9project_Platform9Components_Pf9ctl/1443210

2021-02-23 13:11 UTC, sahil-lakhwani approved these changes
LGTM

2021-02-23 13:15 UTC, merged