Private/devidask/prep node platform val code break
platform9/pf9ctl pull request #59
Opened 2021-02-11 07:37 UTC by devidask27

modularised platform validation code

2021-02-11 07:39 UTC, devidask27 commented
TC build link
http://teamcity.platform9.horse:8111/buildConfiguration/Pf9project_Platform9Components_Pf9ctl/1429932

2021-02-11 07:54 UTC, nikhilbandi commented on pkg/pmk/node.go
>  	case strings.Contains(strDataLower, "centos") || strings.Contains(strDataLower, "redhat"):
Would it be better to add the OS names & versions to a config file instead of hardcoding here in the code?

2021-02-11 07:57 UTC, nikhilbandi commented on pkg/pmk/node.go
> +		"cat /etc/*release | grep '(Core)' | grep 'CentOS Linux release' -m 1 | cut -f4 -d ' '")
Would be good if a comment is in place that specifies how a version is extracted from the release file.

2021-02-11 09:27 UTC, anupbarve requested changes

2021-02-11 09:27 UTC, anupbarve commented on pkg/pmk/node.go
> +
As mentioned earlier, these functions should be moved to pkg/platform/<centos/debian> respectively.

2021-02-11 09:28 UTC, devidask27 commented on pkg/pmk/node.go
> +
yes

2021-02-11 09:29 UTC, devidask27 commented on pkg/pmk/node.go
> +		"cat /etc/*release | grep '(Core)' | grep 'CentOS Linux release' -m 1 | cut -f4 -d ' '")
Okay

2021-02-11 09:39 UTC, anupbarve commented on pkg/pmk/node.go
>  	case strings.Contains(strDataLower, "centos") || strings.Contains(strDataLower, "redhat"):
Move it to constants file instead.

2021-02-12 05:34 UTC, devidask27 commented on pkg/pmk/node.go
> +
Moved this functions to respective platforms
TC build link 
http://teamcity.platform9.horse:8111/buildConfiguration/Pf9project_Platform9Components_Pf9ctl/1431172

2021-02-15 13:51 UTC, anupbarve approved these changes
Overall looks good to me !

2021-02-15 13:51 UTC, anupbarve commented on pkg/pmk/node.go
> +	strDataLower , err := openOSReleaseFile(exec)
%s/strDataLower/strData

Original name doesn't make sense anymore.

2021-02-15 13:51 UTC, anupbarve commented on pkg/pmk/node.go
> +	"github.com/platform9/pf9ctl/pkg/platform"
Could you pls run `go fmt` for all files ?

2021-02-17 04:18 UTC, devidask27 commented
TC build link 
http://teamcity.platform9.horse:8111/buildConfiguration/Pf9project_Platform9Components_Pf9ctl/1435199

2021-02-17 04:45 UTC, anupbarve approved these changes

2021-02-17 04:50 UTC, merged