better error msg
platform9/pf9ctl pull request #60
Opened 2021-02-17 06:58 UTC by sahil-lakhwani

Signed-off-by: sahil-lakhwani <sahilakhwani@gmail.com>

2021-02-17 09:30 UTC, anupbarve requested changes
Please put the console output for the manual testing.
Please also put the TC link.

2021-02-17 09:30 UTC, anupbarve commented on pkg/pmk/common.go
> +		return fmt.Errorf("Unable to edit file /etc/fstab")
This is going to mask the actual errors and make it difficult for us to debug the failures.
Could you also add a debug log with actual err.
Same comment for other instances as well.

2021-02-17 09:30 UTC, anupbarve commented on pkg/platform/centos/centos.go
> -		zap.S().Info(">", err)
Was wondering what this was all about while testing some stuff :) 
Thanks for removing.

2021-02-17 18:03 UTC, sahil-lakhwani commented on pkg/pmk/common.go
> +		return fmt.Errorf("Unable to edit file /etc/fstab")
@anupbarve The debug log for this is printed here https://github.com/platform9/pf9ctl/blob/622631834f501d061efcf78e14b59f67c1fc4f04/pkg/cmdexec/executor.go#L57

2021-02-19 12:30 UTC, anupbarve approved these changes
LGTM

2021-02-19 19:02 UTC, merged