version sub-command modified
platform9/pf9ctl pull request #68
Opened 2021-02-19 13:58 UTC by AnirudhPokala

The version sub-command is printing the current version of CLI being used.

2021-02-19 14:11 UTC, anupbarve requested changes

2021-02-19 14:11 UTC, anupbarve commented on cmd/version.go
> +		fmt.Println("PF9CTL v1.0.0")
Put the version string in constants.go.

2021-02-19 19:05 UTC, sahil-lakhwani commented on cmd/version.go
> +		fmt.Println("PF9CTL v1.0.0")
should the CLI be always addressed in lower case - `pf9ctl`?

2021-02-21 12:07 UTC, AnirudhPokala commented on cmd/version.go
> +		fmt.Println("PF9CTL v1.0.0")
done anup added the version string in constants.go

2021-02-21 12:08 UTC, AnirudhPokala commented on cmd/version.go
> +		fmt.Println("PF9CTL v1.0.0")
changed sahil to lower case.

2021-02-21 15:44 UTC, anupbarve approved these changes
As a general rule, please add the console output in the description field going forward.
LGTM

2021-02-21 16:10 UTC, AnirudhPokala commented
> As a general rule, please add the console output in the description field going forward.
> LGTM

Sure 
[centos@pokala f1]$ sudo ./pf9ctl version
pf9ctl v1.0

2021-02-21 16:21 UTC, merged