integrated check-node in prep-node
platform9/pf9ctl pull request #80
Opened 2021-02-23 14:11 UTC by AnirudhPokala

Integrated check-node in prep-node. 

<img width="568" alt="Screenshot 2021-02-23 at 7 37 56 PM" src="https://user-images.githubusercontent.com/77390180/108855412-fcede180-760e-11eb-9aae-0de09691d1c9.png">

2021-02-23 14:20 UTC, nikhilbandi commented on cmd/checkNode.go
> +	defer c.Segment.Close()
Why have we deferred the closing of Segment here and at other places?

2021-02-23 14:22 UTC, nikhilbandi commented on cmd/prepNode.go
> +		zap.S().Fatalf("Checknode - Failed: %s\n", err.Error())
Better error message is- "Pre-requisite check failed:"

2021-02-23 14:23 UTC, AnirudhPokala commented on cmd/checkNode.go
> +	defer c.Segment.Close()
Before adding differ statement I got this, since we are closing the segment in checknode.go 

<img width="568" alt="Screenshot 2021-02-23 at 7 49 46 PM" src="https://user-images.githubusercontent.com/77390180/108857058-af727400-7610-11eb-80d9-62dde3656d52.png">

2021-02-23 14:24 UTC, AnirudhPokala commented on cmd/prepNode.go
> +		zap.S().Fatalf("Checknode - Failed: %s\n", err.Error())
sure will update it.

2021-02-23 14:30 UTC, AnirudhPokala commented on cmd/checkNode.go
> +	defer c.Segment.Close()
> Why have we deferred the closing of Segment here and at other places?

Because I have removed the segment closing part in pkg/pmk/checkNode.go, so when we will call the checknode command then its segment will not be closed. so added the differ in checknode.go also.

2021-02-23 14:33 UTC, AnirudhPokala commented on cmd/prepNode.go
> +		zap.S().Fatalf("Checknode - Failed: %s\n", err.Error())
Done nikhil modified the error message.

2021-02-24 04:55 UTC, anupbarve reviewed
We should also remove the following client close call in prep-node flow to avoid multiple closures.
https://github.com/platform9/pf9ctl/blob/master/pkg/pmk/node.go#L24

2021-02-24 04:55 UTC, anupbarve commented on pkg/pmk/checkNode.go
> +	//allClients.Segment.Close()
Remove.

2021-02-24 04:55 UTC, anupbarve commented on cmd/prepNode.go
> +	_, err = pmk.CheckNode(ctx, c)
CheckNode is considered to fail if it returns `False`.
So we should not let the prep-node flow continue in 2 cases.
- If an error is encountered. (This you have covered.)
- If checkNode returns False. (This needs to be implemented.)

2021-02-24 04:57 UTC, anupbarve requested changes
Please also put the failure case in the description, where user runs prep-node command and checkNode fails.

2021-02-24 05:44 UTC, AnirudhPokala commented on pkg/pmk/checkNode.go
> +	//allClients.Segment.Close()
Sure anup.

2021-02-24 07:48 UTC, AnirudhPokala commented
> Please also put the failure case in the description, where user runs prep-node command and checkNode fails.

<img width="568" alt="Screenshot 2021-02-24 at 1 16 21 PM" src="https://user-images.githubusercontent.com/77390180/108965321-b8138a80-76a2-11eb-9643-2cdf24c147d8.png">

2021-02-24 09:49 UTC, anupbarve requested changes
Minor comments. Will approve once addressed.

2021-02-24 09:49 UTC, anupbarve commented on pkg/pmk/node.go
> +	//allClients.Segment.Close()
Please delete these.

2021-02-24 09:49 UTC, anupbarve commented on pkg/pmk/checkNode.go
> +	//allClients.Segment.Close()
Please delete this instead of commenting-out.

2021-02-24 09:49 UTC, anupbarve commented on cmd/prepNode.go
> +		zap.S().Fatalf("Check node - Failed\n")
Make this:
Pre-requisite check(s) failed.

2021-02-24 09:49 UTC, anupbarve commented on cmd/prepNode.go
> +		zap.S().Fatalf("Pre-requisite check failed %s\n", err.Error())
s/check/check(s)

2021-02-24 10:03 UTC, anupbarve approved these changes

2021-02-24 10:05 UTC, merged