If user provides wrong credentials will verify and re-ask if invalid during setting config
platform9/pf9ctl pull request #99
Opened 2021-02-26 14:44 UTC by AnirudhPokala

* Added the validation of credentials during config setting ( config, check-node, prep-node command), and will re-run the config setting if not entered valid user credentials. 
* Removed the redundancy of authentication token generation during check-node, and created a new argument auth for checkNode function.
<img width="710" alt="Screenshot 2021-02-26 at 8 03 53 PM" src="https://user-images.githubusercontent.com/77390180/109313989-cd3d1480-786e-11eb-9073-37b133e46db2.png">

2021-03-01 06:46 UTC, anupbarve requested changes

2021-03-01 06:46 UTC, anupbarve commented on cmd/checkNode.go
> +	)
Please put a comment around what each of these fields indicates.

2021-03-01 06:46 UTC, anupbarve commented on cmd/checkNode.go
> +			zap.S().Debug("Invalid credentials entered (Username/Password/Tenant)")
Could you also put this case in the description. It is not clear to me whether a user will get this error on the console ? From the looks of it, the user won't get any warning/error on the console.

2021-03-01 06:46 UTC, anupbarve commented on cmd/config.go
> +		ctx  pmk.Config
Need a good name for flag, add some comment.

2021-03-01 06:46 UTC, anupbarve commented on cmd/checkNode.go
> +	)
Also, need a more intuitive name for `flag`.

2021-03-01 06:46 UTC, anupbarve commented on cmd/prepNode.go
> +		}
I remember that we had discussed about getting this redundant code in a common function.
What happened to that ? Did you hit any roadblocks ?

2021-03-01 06:46 UTC, anupbarve commented on pkg/pmk/config.go
> +*/
Remove or (Enable and reuse) :)

2021-03-01 06:48 UTC, AnirudhPokala commented on pkg/pmk/config.go
> +*/
sure anup will remove, its not working actually, i will discuss during standup

2021-03-01 07:10 UTC, AnirudhPokala commented on cmd/checkNode.go
> +			zap.S().Debug("Invalid credentials entered (Username/Password/Tenant)")
Ya anup, actually its getting into log so changed it now to get in on the console if entered invalid credentials.

2021-03-01 07:10 UTC, AnirudhPokala commented on cmd/config.go
> +		ctx  pmk.Config
Ya modified to credentialsFlag.

2021-03-01 07:27 UTC, AnirudhPokala commented on cmd/prepNode.go
> +		}
Ya anup, i had tried but there was an issue, will discuss with you.

2021-03-01 09:32 UTC, AnirudhPokala commented on cmd/checkNode.go
> +	)
Ya done anup had put the comments where needed.

2021-03-01 12:08 UTC, AnirudhPokala commented on cmd/prepNode.go
> +		}
Ya anup wrapped up the loading and validating into a function.

2021-03-08 13:11 UTC, closed without merging

2021-03-08 13:12 UTC, AnirudhPokala commented
Due to many changes made after this PR, it was creating too many merge conflicts. So raised a new PR.